services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Wtl\HioTypo3Connector\:
    resource: '../Classes/*'
  Wtl\HioTypo3Connector\Controller\PublicationController:
    tags: ['backend.controller']
  Wtl\HioTypo3Connector\Controller\ProjectController:
    tags: ['backend.controller']
  Wtl\HioTypo3Connector\Command\DoctoratesImportCommand:
    tags:
      - name: console.command
        command: 'hio:doctorates:import'
        description: 'Import doctorate data from HISinOne'
  Wtl\HioTypo3Connector\Command\HabilitationsImportCommand:
    tags:
      - name: console.command
        command: 'hio:habilitations:import'
        description: 'Import habilitation data from HISinOne'
  Wtl\HioTypo3Connector\Command\PatentsImportCommand:
    tags:
      - name: console.command
        command: 'hio:patents:import'
        description: 'Import patent data from HISinOne'
  Wtl\HioTypo3Connector\Command\PersonsImportCommand:
    tags:
      - name: console.command
        command: 'hio:persons:import'
        description: 'Import person data from HISinOne'
  Wtl\HioTypo3Connector\Command\ProjectsImportCommand:
    tags:
      - name: console.command
        command: 'hio:projects:import'
        description: 'Import project data from HISinOne'
  Wtl\HioTypo3Connector\Command\PublicationsImportCommand:
    tags:
      - name: console.command
        command: 'hio:publications:import'
        description: 'Import publication data from HISinOne'

  Wtl\HioTypo3Connector\Command\RequestHioPublicationImportCommand:
    tags:
      - name: console.command
        command: 'hio:request:publication:import'
        description: 'Request Import of publication data'
  Wtl\HioTypo3Connector\Command\RequestHioPersonImportCommand:
    tags:
      - name: console.command
        command: 'hio:request:person:import'
        description: 'Request Import of person data'

  Wtl\HioTypo3Connector\EventListener\ReceiveHioDoctorateListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioDoctorateListener'
  Wtl\HioTypo3Connector\EventListener\ReceiveHioHabilitationListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioHabilitationListener'
  Wtl\HioTypo3Connector\EventListener\ReceiveHioPatentListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioPatentListener'
  Wtl\HioTypo3Connector\EventListener\ReceiveHioPersonListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioPersonListener'
  Wtl\HioTypo3Connector\EventListener\ReceiveHioProjectListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioProjectListener'
  Wtl\HioTypo3Connector\EventListener\ReceiveHioPublicationListener:
    tags:
      - name: event.listener
        identifier: 'receiveHioPublicationListener'

  Wtl\HioTypo3Connector\EventListener\AttachHioPublicationToHioPersonsListener:
    tags:
      - name: event.listener
        identifier: 'attachHioPublicationToHioPersonsListener'
