name: 'Publish to Release Repository'

on:
  release:
    types: [created] # Löst die Action nur aus, wenn ein neues Release erstellt wird

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Dev Repo'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Notwendig, um alle Tags und Branches zu holen

      - name: 'Push to Release Repo'
        env:
          RELEASE_REPO_TOKEN: ${{ secrets.RELEASE_REPO_TOKEN }}
          RELEASE_REPO_URL: 'https://github.com/wtl-public/hio-typo3-connector.git' # Passe dies an
          DEV_REPO_URL: 'https://github.com/${{ github.repository }}.git'
        run: |
          # Konfiguriere Git mit dem Token
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote add release_repo "${{ env.RELEASE_REPO_URL }}"
          
          # Pushe den Code-Stand des ausgelösten Releases zum ReleaseRepo
          git push release_repo "${{ github.ref_name }}":main --force --no-tags
          
          # Pushe den spezifischen Tag zum ReleaseRepo
          git push release_repo "${{ github.ref_name }}"

      - name: 'Create Release in Release Repo'
        uses: softprops/action-gh-release@v2
        with:
          repository: 'DEIN_BENUTZERNAME/ReleaseRepo' # Passe dies an
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          draft: false
