name: Sync Release to Production

on:
  release:
    types: [published]

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout development repository
        uses: actions/checkout@v4

      - name: 🚚 Checkout release repository
        uses: actions/checkout@v4
        with:
          repository: wtl-public/hio-typo3-connector
          path: release-repo
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
          ref: main  # Branch, auf dem die Releases erstellt werden sollen

      - name: 🕵️‍♂️ DEBUG-Schritt
        run: |
          echo "--- DEBUG-Informationen ---"
          echo "Wechsle in das 'release-repo' Verzeichnis..."
          cd release-repo
          echo "Aktuelles Verzeichnis: $(pwd)"
          echo ""
          echo ">>> git status"
          git status
          echo ""
          echo ">>> git branch -a (zeigt alle lokalen und remote Branches)"
          git branch -a
          echo ""
          echo ">>> git remote -v (zeigt die Remote-URL)"
          git remote -v
          echo "--- Ende der DEBUG-Informationen ---"

      - name: 🔄 Synchronize files
        run: |
          # Löscht alte Dateien im geklonten Release-Repo (außer .git-Verzeichnis)
          find release-repo -mindepth 1 ! -name '.git' -exec rm -rf {} +
          # Kopiert alle Dateien (außer .git) vom Entwicklungs- ins Release-Repo
          rsync -av --progress . release-repo/ --exclude .git --exclude .github

      - name: ⬆️ Commit and push to release repository
        run: |
          cd release-repo
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          # Commit nur, wenn es Änderungen gibt
          if ! git diff --staged --quiet; then
            git commit -m "chore: Sync from development release ${{ github.event.release.tag_name }}"
            git push origin main
          else
            echo "Keine Änderungen zum Committen."
          fi

      - name: 🎉 Create Release in release repository
        uses: softprops/action-gh-release@v2
        with:
          repository: wtl-public/hio-typo3-connector
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          token: ${{ secrets.RELEASE_REPO_TOKEN }}
